apiVersion: v1
kind: ServiceAccount
metadata:
  name: boxit-server
  namespace: boxit-system
  labels:
    app: boxit

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: boxit-server
  namespace: boxit-system
  labels:
    app: boxit
rules:
- apiGroups:
  - camel.apache.org
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: boxit-server
  namespace: boxit-system
  labels:
    app: boxit
subjects:
- kind: ServiceAccount
  name: boxit-server
roleRef:
  kind: Role
  name: boxit-server
  apiGroup: rbac.authorization.k8s.io
